language: go
go:
 - 1.17.4

branches:
  only: 
    - master

services:
  - docker

stages:
  - Test

jobs:
  include:

    - stage: Test
      before_script:
        - go get github.com/mattn/goveralls
      script:
        - go test $(go list ./... | grep -v /examples/) -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
